/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author zk-de
 */
public class CountWords extends JDialog {

    /**
     * Creates new form CountWords
     */
    public CountWords() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    void initComponents() {
        labelChar = new JLabel();
        labelWords = new JLabel();
        countButton = new JButton();
        JLabel labelCount = new JLabel();
        setIconImage(Toolkit.getDefaultToolkit().getImage("src\\img\\word_count_new.png"));
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zliczanie znaków i słów");
        setLocation(new Point(600, 220));
        labelChar.setFont(new Font("Tahoma", Font.PLAIN, 16)); // NOI18N
        labelChar.setText("Znaki : ");
        labelWords.setFont(new Font("Tahoma", Font.PLAIN, 16)); // NOI18N
        labelWords.setText("Słowa : ");
        countButton.setFont(new Font("Tahoma", Font.PLAIN, 16)); // NOI18N
        countButton.setText("Zlicz");
        countButton.addActionListener(this::countButtonActionPerformed);
        labelCount.setFont(new Font("Tahoma", Font.PLAIN, 18)); // NOI18N
        labelCount.setHorizontalAlignment(SwingConstants.LEFT);
        labelCount.setText("Ilość znaków i słow w tekście");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelCount, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(countButton, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE))
                                        .addComponent(labelWords, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelChar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelCount)
                                        .addComponent(countButton))
                                .addGap(4, 4, 4)
                                .addComponent(labelChar)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelWords)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void countButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if(evt.getSource() == countButton) {
            String text = Frame.textArea.getText();
            labelChar.setText("Znaki : " + text.length());
            String[] words = text.split("\\s");
            labelWords.setText("Słowa : " + words.length);
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton countButton;
    private javax.swing.JLabel labelChar;
    private javax.swing.JLabel labelWords;
    // End of variables declaration

}
